/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2.ui;

import java.util.Hashtable;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Niklas Persson <niklas.persson@gmail.com>
 */
public class SimulationUI extends javax.swing.JFrame {

    /**
     * Creates new form SimulationUI
     */
    public SimulationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulationPanel = new SimulationPanel((SimulationUI) this);
        infoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        controlPanel = new javax.swing.JPanel();
        populationLabel = new javax.swing.JLabel();
        populationText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        widthText = new javax.swing.JTextField();
        heightText = new javax.swing.JTextField();
        vaccinatedCheck = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        infectedRangeText = new javax.swing.JTextField();
        initSickProbSlider = new javax.swing.JSlider();
        Hashtable labelTable = new Hashtable();
        labelTable.put(new Integer(0), new JLabel("0.0") );
        labelTable.put(new Integer(50), new JLabel("0.5") );
        labelTable.put(new Integer(100), new JLabel("1.0") );
        initSickProbSlider.setLabelTable(labelTable);
        initSickProbSlider.setPaintLabels(true);
        jLabel5 = new javax.swing.JLabel();
        daysImmuneText = new javax.swing.JTextField();
        infectProbSlider = new javax.swing.JSlider();
        labelTable = new Hashtable();
        labelTable.put(new Integer(0), new JLabel("0.0") );
        labelTable.put(new Integer(50), new JLabel("0.5") );
        labelTable.put(new Integer(100), new JLabel("1.0") );
        infectProbSlider.setLabelTable(labelTable);
        infectProbSlider.setPaintLabels(true);
        getWellProbSlider = new javax.swing.JSlider();
        labelTable = new Hashtable();
        labelTable.put(new Integer(0), new JLabel("0.0") );
        labelTable.put(new Integer(50), new JLabel("0.5") );
        labelTable.put(new Integer(100), new JLabel("1.0") );
        getWellProbSlider.setLabelTable(labelTable);
        getWellProbSlider.setPaintLabels(true);
        deadProbSlider = new javax.swing.JSlider();
        labelTable = new Hashtable();
        labelTable.put(new Integer(0), new JLabel("0.0") );
        labelTable.put(new Integer(50), new JLabel("0.5") );
        labelTable.put(new Integer(100), new JLabel("1.0") );
        deadProbSlider.setLabelTable(labelTable);
        deadProbSlider.setPaintLabels(true);
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        simulationPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout simulationPanelLayout = new javax.swing.GroupLayout(simulationPanel);
        simulationPanel.setLayout(simulationPanelLayout);
        simulationPanelLayout.setHorizontalGroup(
            simulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        simulationPanelLayout.setVerticalGroup(
            simulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(simulationPanel, java.awt.BorderLayout.CENTER);

        infoPanel.setPreferredSize(new java.awt.Dimension(495, 200));

        outputText.setColumns(20);
        outputText.setRows(5);
        jScrollPane1.setViewportView(outputText);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(infoPanel, java.awt.BorderLayout.SOUTH);

        controlPanel.setPreferredSize(new java.awt.Dimension(170, 100));

        populationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        populationLabel.setText("Population:");

        populationText.setText("1000");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Width");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Height:");

        widthText.setText("1000");

        heightText.setText("1000");

        vaccinatedCheck.setText("Vaccinated:");
        vaccinatedCheck.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vaccinatedCheck.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        vaccinatedCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinatedCheckActionPerformed(evt);
            }
        });

        simulateButton.setText("Initialize village!");
        simulateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateButtonActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Infected range:");

        infectedRangeText.setText("50");
        infectedRangeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infectedRangeTextActionPerformed(evt);
            }
        });

        initSickProbSlider.setMajorTickSpacing(50);
        initSickProbSlider.setMinorTickSpacing(25);
        initSickProbSlider.setPaintLabels(true);
        initSickProbSlider.setPaintTicks(true);
        initSickProbSlider.setToolTipText("INIT_SICK_PROB");
        initSickProbSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "INIT_SICK_PROB:"));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(infectedRangeText);
        jLabel5.setText("Days immune:");

        daysImmuneText.setText("5");
        daysImmuneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysImmuneTextActionPerformed(evt);
            }
        });

        infectProbSlider.setMajorTickSpacing(50);
        infectProbSlider.setMinorTickSpacing(25);
        infectProbSlider.setPaintLabels(true);
        infectProbSlider.setPaintTicks(true);
        infectProbSlider.setToolTipText("INIT_SICK_PROB");
        infectProbSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "INFECT_PROB:"));

        getWellProbSlider.setMajorTickSpacing(50);
        getWellProbSlider.setMinorTickSpacing(25);
        getWellProbSlider.setPaintLabels(true);
        getWellProbSlider.setPaintTicks(true);
        getWellProbSlider.setToolTipText("INIT_SICK_PROB");
        getWellProbSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "GET_WELL_PROB:"));

        deadProbSlider.setMajorTickSpacing(50);
        deadProbSlider.setMinorTickSpacing(25);
        deadProbSlider.setPaintLabels(true);
        deadProbSlider.setPaintTicks(true);
        deadProbSlider.setToolTipText("INIT_SICK_PROB");
        deadProbSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "DEAD_PROB:"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Simulation");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simulateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(initSickProbSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(getWellProbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(infectProbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(deadProbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(populationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(daysImmuneText)
                            .addComponent(infectedRangeText)
                            .addComponent(populationText)
                            .addComponent(widthText)
                            .addComponent(heightText)))
                    .addComponent(vaccinatedCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(populationLabel)
                    .addComponent(populationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(infectedRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(daysImmuneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(vaccinatedCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initSickProbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getWellProbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deadProbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infectProbSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simulateButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vaccinatedCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinatedCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinatedCheckActionPerformed

    private void simulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateButtonActionPerformed
        try {
            SimulationPanel simulation = (SimulationPanel) simulationPanel;
            if (simulateButton.getText().equals("Initialize village!")) {
                int population = Integer.parseInt(populationText.getText());
                int width = Integer.parseInt(widthText.getText());
                int height = Integer.parseInt(heightText.getText());
                boolean vaccinated = vaccinatedCheck.isSelected();
                
                double initSickProb = initSickProbSlider.getValue() / 100.0;
                double getWellProb = getWellProbSlider.getValue() / 100.0;
                double deadProb = deadProbSlider.getValue() / 100.0;
                double infectProb = infectProbSlider.getValue() / 100.0;
                
                int infectRnage = Integer.parseInt(infectedRangeText.getText());
                int daysImmune = Integer.parseInt(daysImmuneText.getText());
                
                simulation.initialize(population, width, height, vaccinated, initSickProb, getWellProb, deadProb, infectProb, infectRnage, daysImmune);
                
                simulateButton.setText("Start simulation!");
            } else {
                simulateButton.setText("Simulation is running...");
                
                simulation.start();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), e.getClass().getName(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_simulateButtonActionPerformed

    private void infectedRangeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infectedRangeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infectedRangeTextActionPerformed

    private void daysImmuneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysImmuneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysImmuneTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JTextField daysImmuneText;
    private javax.swing.JSlider deadProbSlider;
    private javax.swing.JSlider getWellProbSlider;
    private javax.swing.JTextField heightText;
    private javax.swing.JSlider infectProbSlider;
    private javax.swing.JTextField infectedRangeText;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JSlider initSickProbSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public final javax.swing.JTextArea outputText = new javax.swing.JTextArea();
    private javax.swing.JLabel populationLabel;
    private javax.swing.JTextField populationText;
    public final javax.swing.JButton simulateButton = new javax.swing.JButton();
    private javax.swing.JPanel simulationPanel;
    private javax.swing.JCheckBox vaccinatedCheck;
    private javax.swing.JTextField widthText;
    // End of variables declaration//GEN-END:variables
}
